### ISSUE TITLE
OK vs. Not found: mlp.pb

### ISSUE THREAD

**Issue by aqeeliqbal** [tebesu/Tensorflow-Cpp-API-Training#2]
i am testing your code on Xcode 8.2 with mac 10.11.6.
`TF_CHECK_OK(ReadBinaryProto(Env::Default(), graph_definition, &graph_def));` this line gives me a crash. 
`Check failed: ::tensorflow::Status::OK() == (ReadBinaryProto(Env::Default(), graph_definition, &graph_def)) (OK vs. Not found: mlp.pb)`

Any idea why it is doing so?

**Comment by tebesu** [comment]
I think it cannot find the protobuf file. 

Make sure the mlp.pb is in the same directory that you are executing the program. Or you could hard code the directory to the file. 

To hard code it change 
std::string graph_definition = "mlp.pb";

to the absolute directory eg
std::string graph_definition = "/Users/Name/Downloads/mlp.pb";

then recompile and try to run it.
