### ISSUE TITLE
Create Model file for Object (face) Recognition in C++

### ISSUE THREAD

**Issue by ashokbugude** [tebesu/Tensorflow-Cpp-API-Training#3]
Hi
I am doing research on face Recognition using tensorflow
Can I please know how how to use the code to create model file for face recognition.

Task (required in C++)
I have 5 folders, each folder has 4 images of a particular person.
I would like to train the images and generate a model file from scratch.
I would then like to use the model file for recognizing one of the 5 persons

Steps followed 
1. https://www.tensorflow.org/tutorials/image_retraining
Issues
1. Its in Python , but I wanted in C++
2. It is not training the model file from scratch

2. https://github.com/tensorflow/models/tree/master/research/inception/inception
Issue Resolved - Model can be trained from scratch
Unresolved Issue - Its in Python , but I wanted in C++

Please help me in creating the model file in C++

**Comment by tebesu** [comment]
The model can be created in python and then loaded by the C++ API. You will still need to find out the Graph Operation names in the model to run the model in C++. I would not recommend creating the model definition in C++, but rather as I did in the blog post. Create it with python and load it in C++. 

I hope this helps you with your research or am I misunderstanding your question?

**Comment by ashokbugude** [comment]
I wanted to create the model in C++ as we are implementing it in a hardware which only understands c++
Thanks anyway for your response
