### ISSUE TITLE
Save Graph after Training

### ISSUE THREAD

**Issue by ashokbugude** [tebesu/Tensorflow-Cpp-API-Training#4]
Can I please know how to save graph in c++ after the training is completed

**Comment by tebesu** [comment]
Create a Saver when constructing the graph, then find the corresponding operation in the node.

Save weights with something like this:
TF_CHECK_OK(session->Run({}, {}, {"saver/save"}, nullptr))

And restoring weights from a saved model:
TF_CHECK_OK(session->Run({}, {}, {"saver/restore_all"}, nullptr));

Note the strings may not reflect the actual node names in your graph.
