### ISSUE TITLE
How does the "init_all_vars_op" mean? What is the definition of this in your python script?

### ISSUE THREAD

**Issue by chouchou1988** [tebesu/Tensorflow-Cpp-API-Training#6]

**Comment by tebesu** [comment]
Please see line 16 in the blog post for the python code https://tebesu.github.io/posts/Training-a-TensorFlow-graph-in-C++-API which is

`init = tf.initialize_variables(tf.all_variables(), name='init_all_vars_op')`

This will initialize all variables in the graph and assign them the initial values. In the current versions of tensorflow this is `tf.global_variables_initializer()`.
